# Generated by Django 5.1.5 on 2025-02-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brange',
            new_name='brande',
        ),
    ]
